[CS docs] - JPS with different number of nodes
vlobzakov/docs pull request #17
Opened 2019-07-09 13:03 UTC by vlobzakov

[CS docs] - JPS with a different number of nodes: https://jelastic.team/browse/JE-37211.
How to pass **count** parameter dynamically

2019-08-28 13:43 UTC, SlavaKatiukha requested changes

2019-08-28 13:43 UTC, SlavaKatiukha commented on docs/creating-manifest/basic-configs.md
> +- `count` *[optional]* - amount of nodes in one group. The default value is 1. To set up the parameter dynamically see an [example](/creating-manifest/visual-settings/#radio-fieldset).
можно при помощи любого визуального элемента задавать количество нод. Ссылка именно на radio-fieldset выглядит странно. Лучше где-то просто сделать отдельный пример (вот здесь: http://docs.cloudscripting.com/creating-manifest/basic-configs/#nodes-definition). Пример можно не только с radio-fieldset, а, например, с http://docs.cloudscripting.com/creating-manifest/visual-settings/#spinner

2019-08-28 13:43 UTC, SlavaKatiukha commented on docs/creating-manifest/visual-settings.md
> +The *radio-fieldset* can be utilized to pass the number of *nodes* to be installed within specified *nodeGroup*. For example:
перенести в http://docs.cloudscripting.com/creating-manifest/basic-configs/#nodes-definition или удалить

2019-08-30 09:51 UTC, vlobzakov commented on docs/creating-manifest/basic-configs.md
> +- `count` *[optional]* - amount of nodes in one group. The default value is 1. To set up the parameter dynamically see an [example](/creating-manifest/visual-settings/#radio-fieldset).
Не вижу как бы последовательности. В тикете https://jelastic.team/browse/JE-37211  сказано что: в CS доке пример привести: как создать разное кол-во нод в зависимости от выбора пользователя?  относительно элегантный способ через "radio-fieldset" меняется inputType=hidden и далее в nodes https://github.com/sych74/mysql-cluster-1/blob/master/manifest.jps.
В чем странность ссылки на элегантный способ не очень понятно?

2019-08-30 09:51 UTC, vlobzakov commented on docs/creating-manifest/visual-settings.md
> +The *radio-fieldset* can be utilized to pass the number of *nodes* to be installed within specified *nodeGroup*. For example:
переношу

2019-08-30 12:29 UTC, vlobzakov commented on docs/creating-manifest/visual-settings.md
> +The *radio-fieldset* can be utilized to pass the number of *nodes* to be installed within specified *nodeGroup*. For example:
перенес

2019-11-15 15:45 UTC, SlavaKatiukha commented on docs/creating-manifest/basic-configs.md
> +- `count` *[optional]* - amount of nodes in one group. The default value is 1. To set up the parameter dynamically see an [example](/creating-manifest/visual-settings/#radio-fieldset).
потому что пример сделан чисто под radio-fieldset и все будут делать только так. 
Также, пример не должен располагаться в Visual Settings внутри radio-fieldset.

2019-11-26 14:21 UTC, vlobzakov commented on docs/creating-manifest/basic-configs.md
> +- `count` *[optional]* - amount of nodes in one group. The default value is 1. To set up the parameter dynamically see an [example](/creating-manifest/visual-settings/#radio-fieldset).
Что то я запутался, что нужно сделать. Сейчас имеем:
в basic-configs/nodes-definition есть описание параметра Сount: The number of nodes can be passed via any field described in visual-settings section.
Далее идет в качестве примеров два манифеста с использованием radio-fieldset and spinner.
Внутри Radio-fieldset примеры никак не относящиеся к параметру count.

2019-11-26 14:40 UTC, vlobzakov commented on docs/creating-manifest/visual-settings.md
> +The *radio-fieldset* can be utilized to pass the number of *nodes* to be installed within specified *nodeGroup*. For example:
здесь вроде как бы вссе сделано

2019-11-26 15:04 UTC, SlavaKatiukha approved these changes

2019-11-26 15:04 UTC, merged