Add-on installation without environment
vlobzakov/docs pull request #18
Opened 2019-07-09 14:06 UTC by vlobzakov

An ability added to create add-on w/o env: https://jelastic.team/browse/JE-22408

2019-11-15 15:35 UTC, SlavaKatiukha requested changes

2019-11-15 15:35 UTC, SlavaKatiukha commented on docs/creating-manifest/basic-configs.md
> +startPage: https://jelastic.com/
```suggestion
startPage: https://example.com/
```

2019-11-15 15:35 UTC, SlavaKatiukha commented on docs/creating-manifest/basic-configs.md
> +## JPS execution without environment
Should be described as `type: install` without `nodes` parameter.
Types description should be changed also (see https://github.com/vlobzakov/docs/pull/18/files#diff-8579cb093488ca3b1e53aa719d602435R20)

2019-11-15 15:35 UTC, SlavaKatiukha commented on docs/creating-manifest/basic-configs.md
> +The JPS manifest can be executed without binding to any environment. The envName parameter is not mandatory for API anymore.
```suggestion
The JPS manifest can be executed without binding to any environment.  
```

2019-11-15 15:35 UTC, SlavaKatiukha commented on docs/creating-manifest/basic-configs.md
> +## JPS execution without environment
\+ move the description after `Environment Installation` section

2019-11-15 15:35 UTC, SlavaKatiukha commented on docs/creating-manifest/basic-configs.md
> +  "startPage": "https://jelastic.com/",
```suggestion
  "startPage": "https://example.com/",
```

2019-11-26 12:53 UTC, vlobzakov commented on docs/creating-manifest/basic-configs.md
> +## JPS execution without environment
> + move the description after `Environment Installation` section

done

2019-11-26 12:56 UTC, vlobzakov commented on docs/creating-manifest/basic-configs.md
> +## JPS execution without environment
> Should be described as `type: install` without `nodes` parameter.
> Types description should be changed also (see https://github.com/vlobzakov/docs/pull/18/files#diff-8579cb093488ca3b1e53aa719d602435R20)

Could you clarify what should be changed exactly?

2019-12-04 08:29 UTC, SlavaKatiukha approved these changes

2019-12-04 08:29 UTC, merged

2019-12-04 09:32 UTC, SlavaKatiukha commented on docs/creating-manifest/basic-configs.md
> +## JPS execution without environment
see: https://github.com/vlobzakov/docs/blame/master/docs/creating-manifest/basic-configs.md#L20

2019-12-04 12:24 UTC, vlobzakov commented on docs/creating-manifest/basic-configs.md
> +## JPS execution without environment
что то я так и не понял суть коммента и в чем неточность. Можешь пояснить?