Async script action description
vlobzakov/docs pull request #61
Opened 2019-08-21 11:10 UTC by vlobzakov

This is the third part of https://jelastic.team/browse/JE-22396&&https://jelastic.team/browse/JE-46405 cmd action part described.
The other actions' descriptions are in other requests.

2019-12-03 13:56 UTC, vlobzakov reviewed
Please review.

2019-12-09 08:21 UTC, SlavaKatiukha requested changes

2019-12-09 08:21 UTC, SlavaKatiukha commented on docs/creating-manifest/actions.md
> +But unlike [`install`](#install), [`cmd`](#cmd), or [`api`](#api) actions, the `script` **cannot** use a mixture of different node identifications. For example:
not true. Remove

2019-12-09 12:28 UTC, vlobzakov commented on docs/creating-manifest/actions.md
> +But unlike [`install`](#install), [`cmd`](#cmd), or [`api`](#api) actions, the `script` **cannot** use a mixture of different node identifications. For example:
removed

2019-12-09 12:29 UTC, merged