mixins added
vlobzakov/docs pull request #74
Opened 2019-08-23 14:47 UTC by vlobzakov

JE-49368 Mixins include functionality description

2019-08-28 12:46 UTC, SlavaKatiukha requested changes

2019-08-28 12:46 UTC, SlavaKatiukha commented on docs/creating-manifest/basic-configs.md
> +- `mixins` [optional] - includes(mixes) the functionality and data from one manifest into another by URL or object. The following sections can be mixed:
mixins странно смотрится после "...".
Три точки ставилось как "все остальное".  Когда после "все остальное" прописано еще что-то, да еще и такое объемное, то это странно.
Думаю, Mixins должно быть вынесено отдельной страницей и отдельным пунктом в меню (можно перед Add-ons). В basic configs нужно добавить короткое описание (одна строка) и ссылку на детали.

2019-08-28 13:32 UTC, vlobzakov commented on docs/creating-manifest/basic-configs.md
> +- `mixins` [optional] - includes(mixes) the functionality and data from one manifest into another by URL or object. The following sections can be mixed:
Да кстати там насчет  этих трех точек у меня был вопрос - как то не очень понятно что это. Да и там в конце предложения я убрал два слова "More details" так как более ничего не было после них, т.е. предложение не оконченное. Судя по стилю в конце должно было быть слово "here" в таком формате: [here](../<относительная ссылка куда-то>.
По mixins разместил после этих 3 точек потому что предполагалось размещение нескольких примеров и текста и чтобы не ломать список перечисляемых параметров решил указать в конце списка.
Ок т.е. создаю новый подраздел перед аддонс назваю его Mixins и переношу туда обновление, а перед "..." вставляю элемент списка параметрпов такой как mixins и ссылку с том же самом стиле : "More details [here](/creating-manifest/mixins/)"

2019-08-30 09:00 UTC, vlobzakov commented on docs/creating-manifest/basic-configs.md
> +- `mixins` [optional] - includes(mixes) the functionality and data from one manifest into another by URL or object. The following sections can be mixed:
@SlavaKatiukha Внес предложенные изменения.
Ок т.е. создаю новый подраздел перед аддонс назваю его Mixins и переношу туда обновление, а перед "..." вставляю элемент списка параметрпов такой как mixins и ссылку с том же самом стиле : "More details here"

2019-08-30 13:07 UTC, SlavaKatiukha requested changes

2019-08-30 13:07 UTC, SlavaKatiukha commented on docs/creating-manifest/mixins.md
> +![mixins-log](/img/mixins-log.png)
ссылка относительно корня

2019-08-30 13:16 UTC, merged