Data processing placholders description
vlobzakov/docs pull request #86
Opened 2019-09-02 17:49 UTC by vlobzakov

2019-11-15 13:37 UTC, SlavaKatiukha requested changes

2019-11-15 13:37 UTC, SlavaKatiukha commented on docs/creating-manifest/placeholders.md
> +This placeholder returns an array of words or objects in JSON format.
```suggestion
This placeholder returns structured data in JSON format. 
```

2019-11-15 13:37 UTC, SlavaKatiukha commented on docs/creating-manifest/placeholders.md
> +This placeholder acts a regex that finds substring in a string.
```suggestion
This placeholder is used for checking if the specified element exists in the given list or not.  
```

2019-11-15 13:37 UTC, SlavaKatiukha commented on docs/creating-manifest/placeholders.md
> +The result of such regex action is a boolean value: *true* or *false*:
```suggestion
The result of such action is a Boolean value: *true* or *false*:
```

2019-11-15 13:37 UTC, SlavaKatiukha commented on docs/creating-manifest/placeholders.md
> +Compare the output with this:
confusing

2019-11-26 16:06 UTC, vlobzakov commented on docs/creating-manifest/placeholders.md
> +Compare the output with this:
updated

2019-11-29 08:39 UTC, SlavaKatiukha approved these changes

2019-11-29 08:41 UTC, merged