[JPS:Visual Settings] - tooltips support
vlobzakov/docs pull request #93
Opened 2019-09-16 13:23 UTC by vlobzakov

https://jelastic.team/browse/JE-47560

2019-11-15 14:48 UTC, SlavaKatiukha requested changes

2019-11-15 14:48 UTC, SlavaKatiukha commented on docs/creating-manifest/visual-settings.md
> +        - `email` - keystroke filter mask applied to email input. The default value is *'/[a-z0-9_.-+\'@]/i'*. See [appropriate method](http://docs.sencha.com/extjs/3.4.0/#!/api/Ext.form.VTypes-metho
```suggestion
        - `email` - keystroke filter mask applied to email input. The default value is *'/[a-z0-9_.-+\'@]/i'*
```

2019-11-15 14:48 UTC, SlavaKatiukha commented on docs/creating-manifest/visual-settings.md
> +  * **y** [optional] - top coordinate of question mark icon in pixels. Applicable only for tooltips with
remove

2019-11-20 13:38 UTC, vlobzakov commented
requested changed performed

2019-11-20 13:59 UTC, merged